### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by xnekv03** [mangoweb-sylius/SyliusSMSManagerPlugin#1]
Hello,
would it be possible to add this package to https://packagist.org ?

Thanks

Vojta

**Comment by hornofj** [comment]
@xnekv03 it's already there - see the first installation step in README. In case you need the direct link, it's here:
https://packagist.org/packages/mangoweb-sylius/sylius-smsmanager-plugin

**Comment by xnekv03** [comment]
thanks for letting me know
